<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-HFVN6AVE" failures="2" tests="9" name="Test" time="0.037" errors="0" timestamp="2023-04-19T12:35:49 IST">
  <testcase classname="testNg.FailedTestCase" name="t1" time="0.007">
    <skipped/>
  </testcase> <!-- t1 -->
  <testcase classname="testNg.FailedTestCase" name="t1" time="0.0">
    <skipped/>
  </testcase> <!-- t1 -->
  <testcase classname="testNg.FailedTestCase" name="t1" time="0.0">
    <skipped/>
  </testcase> <!-- t1 -->
  <testcase classname="testNg.FailedTestCase" name="t1" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testNg.FailedTestCase.t1(FailedTestCase.java:14)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- t1 -->
  <testcase classname="testNg.FailedTestCase" name="t2" time="0.001"/>
  <testcase classname="testNg.FailedTestCase" name="t3" time="0.0">
    <skipped/>
  </testcase> <!-- t3 -->
  <testcase classname="testNg.FailedTestCase" name="t3" time="0.0">
    <skipped/>
  </testcase> <!-- t3 -->
  <testcase classname="testNg.FailedTestCase" name="t3" time="0.0">
    <skipped/>
  </testcase> <!-- t3 -->
  <testcase classname="testNg.FailedTestCase" name="t3" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testNg.FailedTestCase.t3(FailedTestCase.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- t3 -->
</testsuite> <!-- Test -->
